language: python
python: ["3.8"]

# command to install dependencies
install:
  - pip install flake8
  - pip install pydocstyle
# command to run tests
script:
  - flake8 . --max-line-length=120
  - pydocstyle . --add-ignore=D202
branches:
  only:
    - develop
    - main
    - master
